server:
  port: 58080


#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/statistics_service/
  instance:
    hostname: localhost

#服务的名称
spring:
  application:
    name: statistics-service